name: Docker Publish

on:
  push:
    branches:
      - master  # Cambia esto al nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Iniciar Docker
      run: docker info

    - name: Login en Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build de la imagen de Docker
      run: docker build -t cesardw/prueba2:latest .

    - name: Push de la imagen a Docker Hub
      run: docker push cesardw/prueba2:latest
